config/routes.rb
Rails.application.routes.draw do
  resources :charges
  get 'charges/new'

  get 'charges/create'

  get 'thanks', to: 'charges#thanks', as: 'thanks'

  devise_for :users

  root :to => 'events#index'

  get "hosts/show" => "hosts#show"
  resources :events
  resources :order_items
  resource :cart, only: :show
  resources :orders
end

app/models/account.rb
class Account < ApplicationRecord
  # has_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/stripe_tool.rb
module StripeTool
  def self.create_customer(email: email, stripe_token: stripe_token)
    Stripe::Customer.create(
      email: email,
      source: stripe_token
    )
  end

  def self.create_charge(customer_id: customer_id, amount: amount, description: description)
    Stripe::Charge.create(
      customer: customer_id,
      amount: amount,
      description: description,
      currency: 'usd'
    )
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :order_items

  validates :name, :presence => true
  validates :price, :presence => true
  validates :description, :presence => true
  validates :location, :presence => true
  validates :image, :presence => true
  validates :date, :presence => true
end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :account
  has_many :order_items
  before_save :update_total
  before_create :update_status

  # validates :status, :presence => true
  # validates :account_id, :presence => true
  # validates :total_price, :presence => true

  def calculate_total
    self.order_items.collect { |item| item.event.price * item.quantity }.sum
  end

   private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :event
  belongs_to :order


  validates :quantity, :presence => true
  # validates :event_id, :presence => true
  # validates :order_id, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "Please sign in to visit this page."
      redirect_to '/'
    end
  end

  def authorize_admin
    if current_user.admin === true
      new_event_path
      edit_event_path
      event_path
    else
      flash[:alert] = "Only an admin can visit this page."
      redirect_to '/'
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :amount_to_be_charged, :set_description
  before_action :authenticate_user!


  def new
  end

  def thanks
  end

  def create
    customer = StripeTool.create_customer(email: params[:stripeEmail],
                                          stripe_token: params[:stripeToken])

    charge = StripeTool.create_charge(customer_id: customer.id,
                                      amount: (@amount.round) * 100,
                                      description: @description)
  session[:order_id]=nil
  redirect_to thanks_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private
    def amount_to_be_charged
      @amount = current_order.total_price
    end

    def set_description
      @description = "Some amazing event"
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authorize, :except => [:index]
  before_action :authorize_admin, :only => [:new, :edit, :destroy]

  def index
    @events = Event.all
    @order_item = current_order.order_items.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
 end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event successfully added!"
      respond_to do |format|
      format.html { redirect_to events_url }
      format.js
      end
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event= Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = "Event successfully updated!"
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event successfully deleted!"
    redirect_to events_path
  end

private
  def event_params
    params.require(:event).permit(:image, :name, :location, :date, :price, :description)
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController

  def show
    render template: "hosts/show"
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

def create
  @order = current_order
  @item = @order.order_items.new(item_params)
  @order.save
  session[:order_id] = @order.id
  redirect_to cart_path
end

def show
  @order = current_order
  @item = @order.order_items.find(params[:id])
end

def edit
  @order = current_order
  @item = @order.order_items.find(params[:id])
end

def update
  @order = current_order
  @item = @order.order_items.find(params[:id])
  if @item.update(item_params)
    flash[:notice] = "Cart updated!"
    respond_to do |format|
      format.html { redirect_to cart_path }
      format.js { render "events/show" }
    end
  else
    render :edit
  end
end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    flash[:notice] = "Item deleted!"
    respond_to do |format|
      format.html { redirect_to cart_path }
      format.js
    end
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :event_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def item_total
    total = 0
    current_order.order_items.each do |order_item|
      total += order_item.quantity
    end
    total
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
  def pretty_amount(amount_in_cents)
    number_to_currency(amount_in_cents)
  end
end

app/views/carts/_form.html.erb
<div class ="edit_cart">
  <%= form_for item do |f| %>
    <%= f.hidden_field :event_id, value: item.event_id %>
    <%= f.number_field :quantity %>
    <%= f.submit "Update cart" %>
    <% end %>
</div>

app/views/carts/show.html.erb
<div class="pad">
<h1>Your cart <i class="fa fa-shopping-cart" aria-hidden="true"></i></h1>

<% if @order_items.any? %>
  <% @order_items.each do |item| %>
  <div id='<%= item.id %>'>
      <%= item.event.name %> | <%= link_to "Delete", order_item_path(item), :remote => true, :data => {:confirm => "You sure?", :method => "delete" } %> | <%= link_to 'Edit Cart', edit_order_item_path(item), remote: true %>
    <%= render 'form', :item => item %>
    <p> Unit Price: <%= number_to_currency item.event.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.event.price * item.quantity) %></p>
  <% end %>

  <p>Your Total: <span class="total"><%= number_to_currency current_order.total_price %></span></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>
<p><%= link_to "Check out ", new_charge_path %><i class="fa fa-credit-card" aria-hidden="true"></i></p>
<%= link_to root_path do %>
  <i class="fa fa-undo" aria-hidden="true"></i>
<% end %>
</div>

app/views/charges/new.html.erb
<div class="pad">
<h1>Your Order Total</h1>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= pretty_amount(@amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%= @description %>"
          data-amount="<%= @amount * 100 %>"
          data-email="<%= current_user.email %>"
          data-bitcoin="true"
          data-locale="auto"></script>
<% end %><br>

<%= link_to cart_path do %>
  <i class="fa fa-undo" aria-hidden="true"></i>
<% end %>

</div>

app/views/charges/thanks.html.erb
<div class="pad">
<h2>Thank you for your order! Happy Learning!</h2>
</div

app/views/events/_form.html.erb
<%= render "layouts/errors", :object => @event %>

<%= form_for [@event] do |f| %>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :date %>
  <%= f.text_field :date %>
  <%= f.label :price%>
  <%= f.text_field :price %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.hidden_field(:user_id, :value => current_user.id) %><br>
  <%= f.submit  %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<%= image_tag("paint.jpg", size: "800x500", alt: "Knitting", class: "mainpagePhoto") %>
<br>
<br>
<div class="jumbotron">
<h4>Welcome to LearnHow, your source for finding immersive and interactive events for learning something new.</h4>
<br>

  <div class="buttonCenter">
    <a class="btn btn-basic btn-lg" id="button" role="button">About LearnHow</a>
  </div>
</div>

<div class="about">
  <h5>Our events range from learning how to code, to making fresh pasta from scratch, to budgeting and everything in between. We believe learning alongside fellow neighbors creates a sense of community and camaraderie. We find that learning by observation, and by being hands on, sets a strong foundation for continued learning. All of our hosts are highly experienced in their craft and supply all the materials you'll need. Discover what you can learn and continue to build on your new skills!</h5>
</div>

<hr class="hr">
<div class="padMore">
  <h4>Reviews and Testimonials</h4>
  <br>
  <div class="test1">
    <h6>"I loved learning how to change my oil from a trusted mechanic. It's acutally super easy and I can now do it myself and save money." -Adam S.</h6>
  </div>
  <br>
  <br>
  <div class="test2">
    <h6>"I attended an event for making your own natural beauty products and it was such a great experience. Much better than trying to watch YouTube tutorials and figure out what materials I needed. The host was so knowledgeable and supplied everything I needed to make my own lip balm." -Kelcie M.</h6>
  </div>
  <br>
  <br>
  <div class="test3">
    <h6>"I highly recommend these events. Quick way to learn something cool and perfect for the DIY types. Awesome date night learning how to make fresh pasta from scratch. -Amanda F.</h6>
  </div>
</div>

<br>
<br>
  <h1 class="center">Events</h1>
  <br>
  <br>
  <div class="container">
  <div class="row">
      <% @events.each do |event| %>
      <div class="col-md-6">
        <div class="card" style="width: 20rem;">
          <%= image_tag(event.image, class: "card-img-top", size: "280x220" ) %>
          <br>
          <ul>
          <li><%= link_to event.name, event_path(event) %></li>
          <li><%= event.location %></li>
          <li> <%= event.date %></li>
          <li><%= number_to_currency event.price %></li>
      <br>
      <%= form_for @order_item do |f| %>
        <%= f.hidden_field :event_id, value: event.id %>
        <%= f.number_field :quantity, :class => 'form-control-sm' %>
        <%= f.submit "Add to cart", :class => 'btn btn-basic' %>
        <br>
        <br>
        </div>
      <br>
        <% end %>
      </div>
      <% end %>
      </ul>
    </div>
  </div>
<div class="pad">
  <h3><%= link_to "Admin- New Event", new_event_path %></h3>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form" %>

app/views/events/show.html.erb
<div class="pad">
<%= image_tag(@event.image, class: "mainpagePhoto") %>
<br>
<br>
<h1><%= @event.name %></h1>
<h2><%= @event.location %></h2>
<h2><%= @event.date %></h2>
<h3><%= number_to_currency @event.price %></h3>
<h6><%= @event.description %></h6>
<br>
<p><%= link_to "Return to events", events_path %></p>
<p><%= link_to "Admin- Edit", edit_event_path(@event) %></p>
<p><%= link_to "Admin- Delete", event_path(@event),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
</div>

app/views/hosts/show.html.erb
<div class="pad">
  <h1>Host an Event</h1>

  <h5>Want to host an event through LearnHow?
    <br>
    <br>
    Email us at <em>learnhow@info.com</em> and tell us:
    <br>
    <br>
    (1) the location, date and time (must be at least 2 weeks out and at a public space, try to pick an early evening or afternoon time to cater to more schedules, must be under 4 hours and in the Portland area)
    <br>
    (2) the idea (i.e. I'm a mechanic that would like to teach people how to change their own oil or change a flat tire)
    <br>
    (3) the cost per ticket (most vary from 10-50 per ticket in price depending on materials and if participants get to take something home i.e. the pottery dish they made with your supplied materials)
    <br>
    (4) the max number of people that can attend (however many you can comfortably fit and teach something to)
    <br>
    (5) a phone number where we can reach you to discuss any additional information
    <br>
    <br>
    And voila! We'll get back to you within 24 hours. LearnHow only takes 15% of ticketing sales and 5% of that goes to a different charity each month. The rest goes to the host (and the host must provide all materials). Anything you feel people could enjoy learning more about, just shoot us an email and we can make it happen!
  <br>
  <br>
  <h3>Our charity for December:
  <br>
  Oregon Food Bank
  </h3>

</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnHow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('icon.png'), :rel => 'icon', :type =>  'image/png' %>
    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">
  </head>

  <nav>
    <div class="nav-wrapper">
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <%= image_tag("logo.png", size: "150x150", alt: "Learn How Logo", class: "navPhoto") %>
      </ul>

      <ul>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "Host an Event", hosts_show_path  %></li>
        <li><span class="goAway"><%= item_total %><%= link_to 'Item(s) in Cart', '/cart' %></span></li>
        <li><span class="total"><%=  number_to_currency current_order.total_price %></span></li>
        <% if current_user %>
          <li><%= link_to('Edit User', edit_user_registration_path) %></li>
        <% end %>

        <% if current_user %>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li><%= link_to('Register', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </div>
  </nav>
<br>
<br>
  <body>
  <div>
    <%= flash[:alert] %>
  </div>
  <div>
    <%= flash[:notice] %>
  </div>
    <%= yield %>

  </body>
  <footer class="footer">
    <p>Copyright 2017 Karla Buckner <br>
      Contact: learnhow@info.com | (503) 123-4567 | @learnhow on Instagram</p>
  </footer>
</html>

app/views/order_items/destroy.js.erb
$('#<%= @item.id %>').remove();
  $('.total').html('<%= number_to_currency current_order.total_price %>');
  $('.goAway').html('<%= item_total %>');

app/views/order_items/edit.js.erb
$('.edit_cart').toggle();